version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    restart: always
    networks:
      - mynet

  redis:
    image: redis:7
    expose:
      - "6379"
    restart: always
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

